### ISSUE TITLE
decoy.mock not working with pydantic based class - value is not a valid dict

### ISSUE THREAD

**Issue by samuelint** [mcous/decoy#255] opened 2024-06-12 12:46 UTC
Hi, I have the following problem.

### Problem
using `decoy.mock(cls=MyPydanticBasedClass)` do not work when creating a **pydantic model** with a **mocked pydantic model**.
The error `value is not a valid dict` happen.

### Example
```python
from decoy import Decoy
from pydantic import BaseModel


class MessageDto(BaseModel):
    id: str
    content: str


class MyObjectDto(BaseModel):
    id: str
    message: MessageDto


class MessageFactory:
    def __init__(self):
        pass

    def create(self, content: str):
        return MessageDto(id="1", content=content)


class MyObjectFactory:
    def __init__(self, message_factory: MessageFactory):
        self.message_factory = message_factory

    def create(self, content: str) -> MyObjectDto:
        message = self.message_factory.create(content=content)
        # !! Error happen here !!
        return MyObjectDto(id="1", message=message)


class TestExample:
    def test_create_pyandantic_object(self, decoy: Decoy):
        message_factory = decoy.mock(cls=MessageFactory)
        instance = MyObjectFactory(message_factory=message_factory)
        message_dto_mock = decoy.mock(cls=MessageDto)

        decoy.when(message_factory.create("hi")).then_return(message_dto_mock)

        result = instance.create("hi")

        assert result is message_dto_mock
```

## Error
```python
validation_error = ValidationError(model='MyObjectDto', errors=[{'loc': ('message',), 'msg': 'value is not a valid dict', 'type': 'type_error.dict'}])
```

## Solution tried
I've tried to mock the `.dict` function and still does not work (`decoy.when(message_dto_mock.dict()).then_return({"id": "1", "content": "hi"})`).

---

Since decoy is **type-checking friendly** I would expect it to work with pydantic and allow me to build a pydantic object using a mocked pydantic `BaseModel` class.

Does someone know how to fix that? Do I have something to do differently or is it an improvement for the library?

Thanks :)

**Comment by mcous** [comment] 2024-06-12 14:11
Hi @samuelint! I can take a look at this sometime this week, but my gut reaction is that you **should not mock Pydantic models or other dataclasses** with Decoy. Instances of these objects represent data/values flowing through your app; you should use Decoy to mock things that act on data (like your `MyObjectFactory` class), never the data itself.

In my teams' usage of Decoy with Pydantic, we'd simply create actual model instances to pass around via mocks. You may also be interested something like [Polyfactory](https://polyfactory.litestar.dev/latest/) to create dummy data objects for testing (though I haven't used it personally)

**Comment by samuelint** [comment] 2024-06-13 00:45
@mcous thanks for your answer, I'll try to use Polyfactory to mock DataModel.

**Comment by mcous** [comment] 2024-06-14 15:34
I've looked into this a little deeper, and the cause of the error in your snippet is that Pydantic itself does not recognize a Decoy mock of a Pydantic model as an instance of a Pydantic model. Decoy mocks fake out `__class__` so that they can pass `instanceof` checks, but they will not do anything more sophisticated than that

Mocking out dataclasses is not an intended use of this library, so I'm going to close this issue as a `wontfix`. Thanks for the feedback and report! I hope Polyfactory is better able to suit you fake data needs

**Closed by mcous** 2024-06-14 15:34 UTC
Labels: wontfix
